[general]
version = 1.1
demon = 3.6.7
name = Two-Pulse ECHO
dconfig = CNIGM0114rev1.cfg
pconfig = CNIGM0114rev1.cfp
specmode = 
normalized = false
starttime = Thu Nov 20 15:54:40 2025
finishtime = Thu Nov 20 15:54:45 2025
totaltime = 0h 0min 5s
tformat = 1
stream_axis = 256
no_auto_save = 0

[text]

[sweep]
transient = T,1024,1,a,b
sweep0 = X,10,1,dummy
sweep1 = P,1,1,RepTime,Sampling,tdelay,f,t90,t180,ModulationFrequency,ModulationBandwidth,tau,idx,amp

[aquisition]
a = ;a;A@DG
b = ;a;B@DG

[params]
dummy = 1 step 1;p;PPL variable
RepTime = 2 ms;p;PPL variable
Sampling = 800 ps;p;Sampling@DG
tdelay = -180 ns;p;PPL variable
f = 500 MHz;p;PPL variable
t90 = 12 ns;p;PPL variable
t180 = 12 ns;p;PPL variable
ModulationFrequency = 500 MHz;p;ModulationFrequency@DG
ModulationBandwidth = 100 MHz;p;ModulationBandwidth@DG
tau = 400 ns;p;PPL variable
idx = 1;p;PPL variable
amp = 0.06;p;PPL variable

[decision]

[streams]
names = Re, Im
units = V, V
dwelltime = 800 ps, 800 ps
triggers = 1
scans = 1, 1

[program]
time tdelay, tau, t90, t180
frequency f
%%phase ph90,ph180
real amp
signal a,b
int idx, dummy


%%ph90 = [0, 0]
%%ph180 = [0, 180]

%%det1 = [a, a]
%%det2 = [b, b]

%%ph90 = [0, 90, 180, 270, 0, 90, 180, 270, 0, 90, 180, 270, 0, 90, 180, 270]
%%ph180 = [0, 0, 0, 0, 90, 90, 90, 90, 180, 180, 180, 180, 270, 270, 270, 270]

%%det1 = [a, a, -a, -a, -a, -a, a, a, b, b, -b, -b, -b, -b, b, b]
%%det2 = [b, b, -b, -b, -b, -b, b, b, -a, -a, a, a, a, a, -a, -a]


%% 4-step phase cycle %% <p>p
%%ph90 = [0, 90, 180, 270]
%%ph180 = [0, 0, 0, 0]
%%det1 = [a, -b, -a, b]
%%det2 = [b, a, -b, -a]

%% 8-step phase cycle %% <p>(p)
%%ph90 = [0, 90, 180, 270, 0, 90, 180, 270]
%%ph180 = [0, 0, 0, 0, 180, 180, 180, 180]
%%det1 = [a, -b, -a, b, a, -b, -a, b]
%%det2 = [b, a, -b, -a, b, a, -b, -a]

%% 16-step phase cycle %% <p><p>
ph90 = [0, 90, 180, 270, 0, 90, 180, 270, 0, 90, 180, 270, 0, 90, 180, 270]
ph180 = [0, 0, 0, 0, 90, 90, 90, 90, 180, 180, 180, 180, 270, 270, 270, 270]
%%det1 = [a, -b, -a, b,  -a, b, a, -b   , a, -b, -a, b,    -a, b, a, -b]
%%det2 = [b, a, -b, -a,  -b, -a, b, a   , b, a, -b, -a,    -b, -a, b, a]
det1 = [a, b, -a, -b,  -a, -b, a, b   , a, b, -a, -b,    -a, -b, a, b]
det2 = [b, -a, -b, a,  -b, a, b, -a   , b, -a, -b, a,    -b, a, b, -a]



set90 = [amp, f, ph90(idx)]
set180 = [amp, f, ph180(idx)]

reference f
trig 100ns
wait 100ns

timezero

awg t90, set90
wait tau - (t90+t180)/2
awg t180, set180
wait tau - t180/2 + tdelay


%%detect a, b
detect det1(idx), det2(idx)

[presetup]

[postsetup]

[eachpoint]

[scope]
dfScopeIntWindowPos = 47
dfScopeIntWindowWidth = 155
dfScopeBaselinePos1 = 750
dfScopeBaselineWidth1 = 200
dfScopeBaselinePos2 = 750
dfScopeBaselineWidth2 = 200
dfScopeBaselineOpt = 0
dfScopeLPFilterCutOff = 100 MHz
dfScopeHPFilterCutOff = 100 MHz

[pack]
PackAxis = 0
MaxSeqPerShot = 0


[warmup]
WarmUp = 0
WarmUpScans = 0
WarmUpTime = 0 s


[processing]
ProcessingAlgorithm = 

[scripts]
ScriptStart = *****
ScriptStart_0 = *****
ScriptStop = *****
ScriptStop_0 = *****


[System]
Shots = 0
XReps = 0
YReps = 0
ZReps = 0
Sum1Reps = 0
Sum2Reps = 0
i = 0
j = 0
k = 0
ArmDelay = 10 ms
MTDelay = 10 ms
Wait = 10 ms
Time = 10 ms
FirstPointDelay = 5 s

[SRC]
FrequencyA = 9.1 GHz
EnableA = On
PowerA = 10 dBm
FrequencyB = 12.326 GHz
EnableB = On
PowerB = 15 dBm
TuneDwTime = 1 ms
Sweep = 10 MHz
Phase = 0 deg

[BRIDGE]
Configuration = On
Frequency = 33.752 GHz
LO1 = 9.1 GHz
LO2 = 12.326 GHz
FrequencyIF = 0 Hz
AWGLO = LO1
RecvLOAtten = 0 dB
VideoGain = 18 dB
RecvAmp = Enable
VideoAmp = Enable
VCA = 0 V
DAC1 = 0 V
Ext1 = Off
Ext2 = Off
Ext3 = Off
Ext4 = Off
Ext5 = Off
Ext6 = Off
Ext7 = Off
Ext8 = Off
IO1 = Off
IO2 = Off
IO3 = Off

[AWG]
Mode = AWG
Clock = 8 GHz
Output1 = On
Output2 = On
Frequency = 500 MHz
Span = 500 MHz
RampDuty = 20 %
RampTime = 9 us
Trigger = Internal
TriggerEdge = Rising

[DG]
Scale = ± 500 mV
Offset = 0 %
Coupling = DC
Bandwidth = No filter
Sampling = 800 ps
TraceLength = 100 us
Delay = 224 ns
Trigger = External0
T_Coupling = DC-50
T_Slope = __/^^
T_Level = 1 V
AcquisitionMode = Averager
ModulationFrequency = 500 MHz
ModulationBandwidth = 100 MHz
ModulationPhase = 74 deg

[FLD]
Control = Remote
AutoControl = Run&Tune
Monitoring = Always
Field = 1.21214 T
FieldOffset = 0 T
FieldAUX = 1.21214 T
SweepRate = 0 T/s
SetFieldRate = Normal
SetDelay = 1 s
SetMode = Sweep
RampComp = 1

[PROBE]
X = 0 m
Y = 0 m
Z = 5 mm
Xoff = 0 m
Yoff = 0 m
Zoff = 0 m
Rate = 4 m/min
SettlingTime = 20 ms
Stepper = Enabled steppers

[sample_info]
sample_info = **T**
sample_info_0 = *****

[exp_info]
template = 
