[general]
version = 1.1
demon = 3.5.8602
name = 3pESEEM
dconfig = CNIGM0114rev1.cfg
pconfig = CNIGM0114rev1.cfp
specmode = 
normalized = false
starttime = Sat Sep 16 16:32:17 2023
finishtime = Sat Sep 16 18:03:41 2023
totaltime = 1h 31min 24s
tformat = 1
stream_axis = 256
no_auto_save = 0

[text]

[sweep]
transient = I,1000,100,a,b
sweep0 = S,8,1,idx
sweep1 = X,1064,1,t
sweep2 = P,1,1,RepTime,Sampling,tdelay,f,t90,amp,ModulationFrequency,ModulationBandwidth,tau

[aquisition]
a = ;a;A@DG
b = ;a;B@DG

[params]
idx = 1 step 1;p;PPL variable
t = 32 ns step 8 ns;p;PPL variable
RepTime = 3 ms;p;PPL variable
Sampling = 400 ps;p;Sampling@DG
tdelay = 0 s;p;PPL variable
f = -500 MHz;p;PPL variable
t90 = 16 ns;p;PPL variable
amp = 0.1;p;PPL variable
ModulationFrequency = 500 MHz;p;ModulationFrequency@DG
ModulationBandwidth = 50 MHz;p;ModulationBandwidth@DG
tau = 186 ns;p;PPL variable

[decision]

[streams]
names = Re, Im
units = V, V
dwelltime = 400 ps, 400 ps
triggers = 1
scans = 1, 1

[program]
time tdelay, tau, t90, t
frequency f
real amp
signal a,b
int idx


%% 8-step phase cycle %% p[p](p) Stoll, Phase cycling in ESEEM
ph1 = [0, 0, 0, 0, 0, 0, 0, 0]
ph2 = [0, 90, 180, 270, 0, 90, 180, 270]
ph3 = [0, 0, 0, 0, 180, 180, 180, 180]
%%det1 = [a, -b, -a, b,  -a, b, a, -b]
%%det2 = [b, a, -b, -a,  -b, -a, b, a]

det1 = [a, b, -a, -b,  -a, -b, a, b]
det2 = [b, -a, -b, a,  -b, a, b, -a]



set1 = [amp, f, ph1(idx)]
set2 = [amp, f, ph2(idx)]
set3 = [amp, f, ph3(idx)]

reference f
trig 100ns
wait 100ns

timezero

awg t90, set1
wait tau - t90
awg t90, set2
wait t - t90
awg t90, set3
wait tau - t90/2 - tdelay

detect det1(idx), det2(idx)

[presetup]

[postsetup]

[eachpoint]

[scope]
dfScopeIntWindowPos = 118
dfScopeIntWindowWidth = 129
dfScopeBaselinePos1 = 750
dfScopeBaselineWidth1 = 200
dfScopeBaselinePos2 = 750
dfScopeBaselineWidth2 = 200
dfScopeBaselineOpt = -1

[pack]
PackAxis = 0
MaxSeqPerShot = 0


[warmup]
WarmUp = 0
WarmUpScans = 0
WarmUpTime = 0 s


[processing]
ProcessingAlgorithm = 

[System]
Shots = 0
XReps = 0
YReps = 0
ZReps = 0
Sum1Reps = 0
Sum2Reps = 0
i = 0
j = 0
k = 0
ArmDelay = 10 ms
MTDelay = 10 ms
Wait = 10 ms
Time = 10 ms

[BRIDGE]
Configuration = 9 GHz
Frequency = 9.4 GHz
LO2 = 8 GHz
RecvAmp = On
AWGLO = External
ATT1 = 0 dB
ATT2 = 0 dB
PHASE2 = 0 deg
VCA = 100 %
Ext1 = Off
Ext2 = Off
Ext3 = Off
Ext4 = Off
Ext5 = Off
Ext6 = Off
Ext7 = Off
Ext8 = Off
IO1 = 0
IO2 = 0
IO3 = 0

[AWG]
Mode = AWG
Clock = 10 GHz
Output1 = On
Output2 = On
Frequency = 100 MHz
Span = 0 Hz
RampTime = 100 us
Trigger = Internal
TriggerEdge = Rising

[DG]
Scale = ± 200 mV
Offset = 0 %
Coupling = DC
Bandwidth = No filter
Sampling = 400 ps
TraceLength = 0 s
Delay = 0 s
Trigger = External1
T_Coupling = DC
T_Slope = __/^^
T_Level = 800 mV
AcquisitionMode = Digitizer
ModulationFrequency = 500 MHz
ModulationBandwidth = 50 MHz
ModulationPhase = 180 deg

[SRC]
FrequencyA = 9.05 GHz
EnableA = On
PowerA = 10 dBm
FrequencyB = 12.4 GHz
EnableB = On
PowerB = 15 dBm
TuneDwTime = 1 ms
Sweep = 10 MHz
Phase = 0 deg

[FLD]
Control = Remote
AutoControl = Run&Tune
Monitoring = Always
Field = 1.21214 T
FieldOffset = 0 T
FieldAUX = 1.21214 T
SweepRate = 0 T/s
SetFieldRate = Normal
SetDelay = 1 s
SetMode = Sweep
RampComp = 1

[sample_info]
sample_info = **T**
sample_info_0 = *****

[exp_info]
template = 
